name: Build and publish Docker image

on:
  push:
    branches: [ main, staging ]

jobs:
  build-and-push-image:
    # The job will only run if one of the commit messages contains [BUILD]
    if: |
      contains(github.event.head_commit.message, '[BUILD]') ||
      contains(join(github.event.commits.*.message), '[BUILD]') ||
      contains(join(github.event.pull_request.commits.*.message), '[BUILD]')
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value={{sha}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.9.0
        with:
          push: true
          file: docker/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}